spring.datasource.url=jdbc:mysql://localhost:3306/devopsmonitoring?useSSL=false&serverTimezone=UTC
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver