apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-monitoring-portal-config

data:
  SPRING_PROFILES_ACTIVE: "prod"

  MYSQL_HOST: "dm-db.mysql.database.azure.com"
  MYSQL_DATABASE: "devopsmonitoring"
  MYSQL_USERNAME: "sarfarazakbar777"

  APP_ENVIRONMENT: "prod"
  APP_VERSION: "1.0.0"
  BUILD_NUMBER: "0"
  BUILD_TIMESTAMP: "2026-01-01T00:00:00"
  IMAGE_TAG: "latest"
  GIT_COMMIT_ID: "unknown"
  BRANCH_NAME: "main"
  DEPLOYMENT_TIME: "2026-01-01T00:00:00"

  ADMIN_USERNAME: "admin"